---
title: "Classificaion for fMRI curves"
# author: "Hyunsung Kim"
date: '2024-05-07'
format: 
  pdf:
    documentclass: scrartcl
    include-in-header:
      - text: |
          \usepackage{kotex}
      - ./preamble.tex
    geometry:
      - top=20mm
      - bottom=25mm
      - left=25mm
      - right=25mm
      - heightrounded
knitr:
  opts_chunk:
    out.width: "80%"
---


```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE, 
  # cache = T,
  # fig.width = 12, fig.height = 6,
  # out.width = "80%",
  fig.align = "center"
)
# # Set working directory
# knitr::opts_knit$set(root.dir = "../")
```

# Functional GLM with sparse group lasso using functional manifold components

- Setting 1: $\alpha = 0.2$, FVE = 0.7, d = 2

- Setting 2: $\alpha = 0.2$, FVE = 0.7

- Setting 3: $\alpha = 0.1$, FVE = 0.7

- Setting 4: $\alpha = 0.1$, FVE = 0.95

\begin{table}[ht]
\centering
\begin{tabular}{crrrr}
\hline
  & Setting 1 & Setting 2 & Setting 3 & Setting 4 \\ 
  \hline
  $d$ & 2 & $14 \sim 15$ & $14 \sim 15$ & $19 \sim 20$ \\
 Accuracy & 0.580 & 0.580 & 0.581 & 0.582  \\ 
 Sensitivity & 0.111 & 0.039 & 0.041 & 0.018 \\
 Specificity & 0.917 & 0.965 & 0.962 & 0.977 \\
  \hline
\end{tabular}
\end{table}





## 문제점

- 이전에 B-spline이나 FPCA를 이용한 Group lasso와 유사하게 모든 $\beta=0$으로 shrinkage 되어 prediction을 1개 class로만 분류해버리는 문제 발생

- 현재 hyperparameter tuning은 하지 않았지만, 급격히 좋아질 것이라 기대되지는 않음

- 데이터의 fluctuatation이 심해서인지 추정된 manifold의 dimension 또한 꽤 커보임
  - 그럼에도 B-spline이나 FPCA으로 차원축소한 것보다는 적은 편임
  
## 다른 방법??

- Xue, K., Yang, J., & Yao, F. (2023). [Optimal linear discriminant analysis for high-dimensional functional data](https://www.tandfonline.com/doi/full/10.1080/01621459.2022.2164288). Journal of the American Statistical Association, 1-10.

- Chiou, J. M., & Müller, H. G. (2014). [Linear manifold modelling of multivariate functional data](https://academic.oup.com/jrsssb/article/76/3/605/7076026). Journal of the Royal Statistical Society Series B: Statistical Methodology, 76(3), 605-626.
